# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_rule.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11update_rule.proto\"#\n\x11UpdateRuleRequest\x12\x0e\n\x06status\x18\x01 \x01(\x08\"&\n\x12UpdateRuleResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1e\n\x0c\x41lertRequest\x12\x0e\n\x06status\x18\x01 \x01(\x08\"!\n\rAlertResponse\x12\x10\n\x08response\x18\x01 \x01(\t2N\n\x11UpdateRuleService\x12\x39\n\nUpdateRule\x12\x12.UpdateRuleRequest\x1a\x13.UpdateRuleResponse(\x01\x30\x01\x32R\n\x18UpdateAlertStatusService\x12\x36\n\x11UpdateAlertStatus\x12\r.AlertRequest\x1a\x0e.AlertResponse(\x01\x30\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_rule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_UPDATERULEREQUEST']._serialized_start=21
  _globals['_UPDATERULEREQUEST']._serialized_end=56
  _globals['_UPDATERULERESPONSE']._serialized_start=58
  _globals['_UPDATERULERESPONSE']._serialized_end=96
  _globals['_ALERTREQUEST']._serialized_start=98
  _globals['_ALERTREQUEST']._serialized_end=128
  _globals['_ALERTRESPONSE']._serialized_start=130
  _globals['_ALERTRESPONSE']._serialized_end=163
  _globals['_UPDATERULESERVICE']._serialized_start=165
  _globals['_UPDATERULESERVICE']._serialized_end=243
  _globals['_UPDATEALERTSTATUSSERVICE']._serialized_start=245
  _globals['_UPDATEALERTSTATUSSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
